# -------------------------------------------------------------------------------------------------
# Maintenance Settings, everything related to maintenance mode.
# -------------------------------------------------------------------------------------------------

Maintenance:
  Enabled: false
  Reason: "Notfall"
  EndTime: "25.12.2026"

